LoyaltyApp/force-app/main/default/objects/Loyalty_Brand__c/Loyalty_Brand__c.object-meta.xml
<CustomObject>
    <label>Loyalty Brand</label>
    <nameField>
        <label>Loyalty Trendmark Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LoyaltyApp/force-app/main/default/objects/Loyalty_Brand__c/fields/Business_Group__c.field-meta.xml
<CustomField>
    <fullName>Business_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Group</label>
    <referenceTo>Loyalty_Business_Group__c</referenceTo>
    <relationshipLabel>Loyalty Brands</relationshipLabel>
    <relationshipName>Loyalty_Brands</relationshipName>
    <type>Lookup</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Brand_Value__c/Loyalty_Brand_Value__c.object-meta.xml
<CustomObject>
    <label>Loyalty Brand Value</label>
    <nameField>
        <label>Loyalty Brand Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Brand Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LoyaltyApp/force-app/main/default/objects/Loyalty_Brand_Value__c/fields/Loyalty_Brand__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Brand__c</fullName>
    <label>Loyalty Brand</label>
    <referenceTo>Loyalty_Brand__c</referenceTo>
    <relationshipLabel>Loyalty Brand Values</relationshipLabel>
    <relationshipName>Loyalty_Brand_Values</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Brand_Value__c/fields/Loyalty_Value__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Value__c</fullName>
    <label>Loyalty Value</label>
    <referenceTo>Loyalty_Value__c</referenceTo>
    <relationshipLabel>Loyalty Brand Values</relationshipLabel>
    <relationshipName>Loyalty_Brand_Values</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Business_Group__c/Loyalty_Business_Group__c.object-meta.xml
<CustomObject>
    <label>Loyalty Business Group</label>
    <nameField>
        <label>Business Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Business Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LoyaltyApp/force-app/main/default/objects/Loyalty_Business_Group__c/fields/Is_Associated_Group__c.field-meta.xml
<CustomField>
    <fullName>Is_Associated_Group__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Associated Group</label>
    <type>Checkbox</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Level__c/Loyalty_Level__c.object-meta.xml
<CustomObject>
    <label>Loyalty Level</label>
    <nameField>
        <label>Loyalty Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Levels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program__c/Loyalty_Program__c.object-meta.xml
<CustomObject>
    <label>Loyalty Program</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program__c/fields/Program_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Program_End_Date__c</fullName>
    <label>Program End Date</label>
    <type>Date</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program__c/fields/Program_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Program_Start_Date__c</fullName>
    <label>Program Start Date</label>
    <type>Date</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Card Program</fullName>
            </value>
            <value>
                <fullName>Hybrid Program</fullName>
            </value>
            <value>
                <fullName>Paid Program</fullName>
            </value>
            <value>
                <fullName>Partnered Program</fullName>
            </value>
            <value>
                <fullName>Point Program</fullName>
            </value>
            <value>
                <fullName>Spend Program</fullName>
            </value>
            <value>
                <fullName>Tiered Program</fullName>
            </value>
            <value>
                <fullName>Value Program</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Member__c/Loyalty_Program_Member__c.object-meta.xml
<CustomObject>
    <label>Loyalty Program Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Program Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Member__c/fields/Loyalty_Level__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Level__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Loyalty Level</label>
    <referenceTo>Loyalty_Level__c</referenceTo>
    <relationshipName>Program_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Member__c/fields/Loyalty_Program__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Program__c</fullName>
    <label>Loyalty Program</label>
    <referenceTo>Loyalty_Program__c</referenceTo>
    <relationshipName>Program_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Member__c/fields/Member__c.field-meta.xml
<CustomField>
    <fullName>Member__c</fullName>
    <label>Member</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Program_Members</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Member__c/fields/Member_Number__c.field-meta.xml
<CustomField>
    <fullName>Member_Number__c</fullName>
    <label>Member Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Reward__c/Loyalty_Reward__c.object-meta.xml
<CustomObject>
    <label>Loyalty Reward</label>
    <nameField>
        <label>Loyalty Reward Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Rewards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LoyaltyApp/force-app/main/default/objects/Loyalty_Reward_Value__c/Loyalty_Reward_Value__c.object-meta.xml
<CustomObject>
    <label>Loyalty Reward Value</label>
    <nameField>
        <label>Loyalty Reward Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Reward Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LoyaltyApp/force-app/main/default/objects/Loyalty_Reward_Value__c/fields/Is_Delivered__c.field-meta.xml
<CustomField>
    <fullName>Is_Delivered__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check if the reward is already delivered to the customer</description>
    <label>Is Delivered</label>
    <type>Checkbox</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Reward_Value__c/fields/Loyalty_Reward__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Reward__c</fullName>
    <label>Loyalty Reward</label>
    <referenceTo>Loyalty_Reward__c</referenceTo>
    <relationshipLabel>Loyalty Reward Values</relationshipLabel>
    <relationshipName>Loyalty_Reward_Values</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Reward_Value__c/fields/Loyalty_Value__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Value__c</fullName>
    <label>Loyalty Value</label>
    <referenceTo>Loyalty_Value__c</referenceTo>
    <relationshipLabel>Loyalty Reward Values</relationshipLabel>
    <relationshipName>Loyalty_Reward_Values</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Reward_Value__c/fields/Reward_Type__c.field-meta.xml
<CustomField>
    <fullName>Reward_Type__c</fullName>
    <description>Type of reward</description>
    <label>Reward Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Benefit</fullName>
                <default>true</default>
                <label>Benefit</label>
            </value>
            <value>
                <fullName>Offer</fullName>
            </value>
            <value>
                <fullName>Voucher</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Value__c/Loyalty_Value__c.object-meta.xml
<CustomObject>
    <label>Loyalty Value</label>
    <nameField>
        <label>Loyalty Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LoyaltyApp/force-app/main/default/objects/Loyalty_Value__c/fields/Customer_Points__c.field-meta.xml
<CustomField>
    <fullName>Customer_Points__c</fullName>
    <label>Customer Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Value__c/fields/Customer_Spend_Points__c.field-meta.xml
<CustomField>
    <fullName>Customer_Spend_Points__c</fullName>
    <description>Used for the spend program. It&apos;s a cumulative value related to the total money spent by the customer</description>
    <label>Customer Spend Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Value__c/fields/Is_Points_Used__c.field-meta.xml
<CustomField>
    <fullName>Is_Points_Used__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Points Used</label>
    <type>Checkbox</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Value__c/fields/Loyalty_Brand_Value__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Brand_Value__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loyalty Brand Value</label>
    <referenceTo>Loyalty_Brand__c</referenceTo>
    <relationshipLabel>Loyalty Values</relationshipLabel>
    <relationshipName>Loyalty_Values</relationshipName>
    <type>Lookup</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Value__c/fields/Loyalty_Business_Group__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Business_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loyalty Business Group</label>
    <referenceTo>Loyalty_Business_Group__c</referenceTo>
    <relationshipLabel>Loyalty Values</relationshipLabel>
    <relationshipName>Loyalty_Values</relationshipName>
    <type>Lookup</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Value__c/fields/Program_Member__c.field-meta.xml
<CustomField>
    <fullName>Program_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Member</label>
    <referenceTo>Loyalty_Program_Member__c</referenceTo>
    <relationshipLabel>Loyalty Values</relationshipLabel>
    <relationshipName>Loyalty_Values</relationshipName>
    <type>Lookup</type>
</CustomField>

LoyaltyApp/force-app/main/default/classes/Loyalty_Test_Ctrl_RewardValuesList.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 02-01-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   02-01-2021   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
@isTest
public with sharing class Loyalty_Test_Ctrl_RewardValuesList {

    private static Id rewardValueId;
    static void populateMockData() {

        List<RecordType> loyaltyProgramRecordTypes = [Select Id From RecordType where sobjecttype = 'Loyalty_Program__c' and Name like '%Spend%'];
        List<RecordType> programMemberRecordTypes = [Select Id From RecordType where sobjecttype = 'Loyalty_Program_Member__c' and Name like '%Spend%'];

        Account acc= new Account();
        acc.Name='account_unitTest';
        insert acc;

        Loyalty_Level__c loyaltyLevel= new Loyalty_Level__c();
        loyaltyLevel.Name='loyaltyLevel_unitTest';
        insert loyaltyLevel;

        Loyalty_Program__c loyaltyProgram= new Loyalty_Program__c();
        loyaltyProgram.Description__c='Loyalty Program used to test Reward Value';
        loyaltyProgram.Name='loyaltyProgram_unitTest';
        loyaltyProgram.Program_Start_Date__c=date.parse('10/08/2020');
        loyaltyProgram.Program_End_Date__c=date.parse('10/08/2021');
        loyaltyProgram.RecordTypeId=loyaltyProgramRecordTypes[0].Id;
        loyaltyProgram.Type__c='Spend Program';
        insert loyaltyProgram;

        Loyalty_Program_Member__c programMember = new Loyalty_Program_Member__c();
        programMember.Is_Active__c=true;
        programMember.Joining_Date__c=date.parse('10/01/2021');
        programMember.Loyalty_Level__c=loyaltyLevel.Id; // lookup
        programMember.Loyalty_Program__c=loyaltyProgram.Id; //lookup
        programMember.Member__c=acc.Id; //lookup
        programMember.Name='program_Member_unitTest';
        programMember.Member_Number__c='dfgdfgd3232424';
        programMember.RecordTypeId = programMemberRecordTypes[0].Id;
        insert programMember;

        Loyalty_Business_Group__c busGrp= new Loyalty_Business_Group__c();
        busGrp.Name='business_Group_unitTest';
        busGrp.Is_Associated_Group__c=false;
        insert busGrp;

        Loyalty_Brand__c loyaltyBrand= new Loyalty_Brand__c();
        loyaltyBrand.Business_Group__c=busGrp.Id; //lookup
        loyaltyBrand.Name='loyaltyBrand_unitTest';
        insert loyaltyBrand;

        Loyalty_Value__c lv= new Loyalty_Value__c();
        lv.Customer_Points__c=100;
        lv.Customer_Spend_Points__c=30;
        lv.Expiration_Date__c=date.parse('10/07/2021');
        lv.Is_Points_Used__c=false;
        lv.Loyalty_Brand_Value__c=loyaltyBrand.Id;//lookup
        lv.Loyalty_Business_Group__c=busGrp.Id;// lookup
        lv.Name='Loyalty_Value_unitTest';
        lv.Program_Member__c=programMember.Id; //lookup
        insert lv;

        Loyalty_Reward__c lr= new  Loyalty_Reward__c();
        lr.Name='Loyalty_Reward_unitTest';
        insert lr;

        Loyalty_Reward_Value__c rewardValueRecord= new Loyalty_Reward_Value__c();
        rewardValueRecord.Name='rewardValueRecord';
        rewardValueRecord.Is_Delivered__c=false;
        rewardValueRecord.Loyalty_Reward__c=lr.Id; //lookup
        rewardValueRecord.Loyalty_Value__c=lv.Id; //lookup
        rewardValueRecord.Reward_Type__c='Offer';
        insert rewardValueRecord;

        rewardValueId=rewardValueRecord.Id;


    }

    @IsTest static void test_Loyalty_Util_RewardValueDml() {
        
        Loyalty_Util_RewardValueDml controller = new Loyalty_Util_RewardValueDml();
    	System.assertNotEquals(controller,null); 
    }


    @IsTest static void getLoyaltyRewardValues() {

        List<Loyalty_Reward_Value__c> returnedRewardValues=new List<Loyalty_Reward_Value__c>();
        Integer pagenumber=1;
        Integer pageSize=10;
        Integer lastRecordPosition=0;
        Boolean isAddedData=false;
        String searchString=null;
        List<String> whereClauses=null;
        String orderByStr='Name';

        Test.startTest();
        populateMockData();    
       
        returnedRewardValues= Loyalty_Ctrl_LoyaltyRewardValuesList.getLoyaltyRewardValues(pagenumber, pageSize, lastRecordPosition, isAddedData, 
        searchString, whereClauses, orderByStr);

    	System.assertEquals(returnedRewardValues.size(),1); 
        Test.stopTest();
    }

    @IsTest static void getLoyaltyRewardValuesCount() {

        List<Loyalty_Reward_Value__c> returnedRewardValues=new List<Loyalty_Reward_Value__c>();
        Integer quantity=0;

        Test.startTest();
        populateMockData();   
        
        returnedRewardValues=[Select Id from Loyalty_Reward_Value__c];
        quantity= Loyalty_Ctrl_LoyaltyRewardValuesList.getLoyaltyRewardValuesCount(null);
        
        System.assertEquals(returnedRewardValues.size(),quantity);      
        Test.stopTest();
    }

    @IsTest static void getRewardValueData() {

       Loyalty_Reward_Value__c returnedRewardValue= new Loyalty_Reward_Value__c();

        Test.startTest();
        populateMockData();   
        
        returnedRewardValue=Loyalty_Ctrl_LoyaltyRewardValuesList.getRewardValueData(rewardValueId);
        
        System.assertNotEquals(returnedRewardValue,null);      
        Test.stopTest();

    }

    @IsTest static void createRewardValue() {

        String returnedName='';
        
        Test.startTest();
        populateMockData();

        String rewardValueJson=JSON.serialize(
            [Select Name, Is_Delivered__c, Loyalty_Reward__c, Loyalty_Value__c, 
            Reward_Type__c from Loyalty_Reward_Value__c limit 1]);

        returnedName= Loyalty_Ctrl_LoyaltyRewardValuesList.createRewardValue(rewardValueJson);
        
        System.assertEquals(returnedName,'rewardValueRecord');      
        Test.stopTest();
    }

    @IsTest static void editRewardValue() {

        String returnedName='';
      
        Test.startTest();
        populateMockData();

        Loyalty_Reward_Value__c rewardValue=[Select Id, Name, Is_Delivered__c, Loyalty_Reward__c, 
        Loyalty_Value__c, Reward_Type__c from Loyalty_Reward_Value__c where Id=:rewardValueId];

        rewardValue.Reward_Type__c='Voucher';

        String rewardValueJson=JSON.serialize(rewardValue);

        returnedName= Loyalty_Ctrl_LoyaltyRewardValuesList.editRewardValue(rewardValueJson);
 
        System.assertNotEquals(null, rewardValueJson);      
        Test.stopTest();
    }

    @IsTest static void changeLoyaltyRewardValueField() {

        Test.startTest();
        populateMockData();  
        
        String result='';
        String field='Reward_Type__c';
        String newFieldValue='Voucher';
        String id=rewardValueId;
        String name='rewardValueRecord';
        
        result= Loyalty_Ctrl_LoyaltyRewardValuesList.changeLoyaltyRewardValueField(
             field, newFieldValue, id, name);
        
        System.assertNotEquals(null, result);    
        Test.stopTest();
    }


            /*
    
    @IsTest static void getLoyaltyRewardValueListViews() {

        List<ListView> rewardValueListViews = new List<ListView>();
        Integer quantity=0;
        Integer quantity2=0;

        Test.startTest();
        populateMockData();   
        
        rewardValueListViews=[Select Id, DeveloperName from ListView where SObjectType = 'Loyalty_Reward_Value__c'];
        quantity= rewardValueListViews.size();
        rewardValueListViews=Loyalty_Ctrl_LoyaltyRewardValuesList.getLoyaltyRewardValueListViews();
        quantity2= rewardValueListViews.size();
        
        System.assertEquals(quantity2,quantity);      
        Test.stopTest();
    }

    */

    
    
  
}