LoyaltyApp/force-app/main/default/objects/Loyalty_Program__c/Loyalty_Program__c.object-meta.xml
<CustomObject>
    <label>Loyalty Program</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>TODAY() &gt;= Program_Start_Date__c  &amp;&amp; TODAY() &lt;= Program_End_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup__c/Loyalty_Program_Setup__c.object-meta.xml
<CustomObject>
    <label>Loyalty Program Setup</label>
    <nameField>
        <label>Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Program Setups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup__c/fields/Loyalty_Program__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Program__c</fullName>
    <label>Loyalty Program</label>
    <referenceTo>Loyalty_Program__c</referenceTo>
    <relationshipLabel>Loyalty Program Setups</relationshipLabel>
    <relationshipName>Loyalty_Program_Setups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

LoyaltyApp/force-app/main/default/classes/Loyalty_Ctrl_LoyaltyProgramSetup.cls
/*
   @Author: André Cunha
   @CreatedDate: 10/07/2020
   @Description: Controller class for loyaltyProgramSetup component
 */
public class Loyalty_Ctrl_LoyaltyProgramSetup {
    
    /*
        @Description: method to get setupId
        @param1: loyalty program id
        @return: return the setupId
	*/
    @AuraEnabled
    public static Id getProgramSetupId(String programId){
        
        Id loyaltyProgramSetupId = [SELECT Id FROM Loyalty_Program_Setup__c WHERE Loyalty_Program__c = :programId AND Active__c = TRUE Limit 1].Id;

        return loyaltyProgramSetupId;
    }
    
    /*
        @Description: method to get program setup id and record type id
        @param1: loyalty program id
        @return: return the object with id and recordTypeId
	*/
    @AuraEnabled
    public static Loyalty_Program_Setup__c getProgramSetupRecordTypeId(String programId){
        
        return [SELECT Id, RecordTypeId FROM Loyalty_Program_Setup__c WHERE Loyalty_Program__c = :programId AND Active__c = TRUE Limit 1];
    }
}