LoyaltyApp/force-app/main/default/objects/Loyalty_Program__c/Loyalty_Program__c.object-meta.xml
<CustomObject>
    <label>Loyalty Program</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>TODAY() &gt;= Program_Start_Date__c  &amp;&amp; TODAY() &lt;= Program_End_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Card Program</fullName>
            </value>
            <value>
                <fullName>Hybrid Program</fullName>
            </value>
            <value>
                <fullName>Paid Program</fullName>
            </value>
            <value>
                <fullName>Partnered Program</fullName>
            </value>
            <value>
                <fullName>Point Program</fullName>
            </value>
            <value>
                <fullName>Spend Program</fullName>
            </value>
            <value>
                <fullName>Tiered Program</fullName>
            </value>
            <value>
                <fullName>Value Program</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup__c/Loyalty_Program_Setup__c.object-meta.xml
<CustomObject>
    <label>Loyalty Program Setup</label>
    <nameField>
        <label>Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Program Setups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup__c/fields/Loyalty_Program__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Program__c</fullName>
    <label>Loyalty Program</label>
    <referenceTo>Loyalty_Program__c</referenceTo>
    <relationshipLabel>Loyalty Program Setups</relationshipLabel>
    <relationshipName>Loyalty_Program_Setups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

LoyaltyApp/force-app/main/default/classes/LoyaltyProgram_tl.cls
/*
   @Author: André Cunha
   @CreatedDate: 07/07/2020
   @Description: Loyalty program trigger logic. Implemented methods with logic
 */
public class LoyaltyProgram_tl {
    private LoyaltyProgram_th handler;

    public LoyaltyProgram_tl(LoyaltyProgram_th handler) {
        this.handler = handler;
    }

    public void createLoyaltyProgramSetup(){

        Set<String> programTypes = new Set<String>();

        for(Loyalty_Program__c loyaltyProgram : handler.getNewMap().values()){
            if(loyaltyProgram.Type__c != null && loyaltyProgram.Type__c != ''){
                String loyaltySetupType = loyaltyProgram.Type__c + ' Setup';
                programTypes.add(loyaltySetupType.replaceAll(' ','_'));
            }
        }

        Map<String,RecordType> mapRecordTypes = new Map<String,RecordType>();

        for(RecordType rt : [SELECT id,Name,DeveloperName,SobjectType From RecordType WHERE DeveloperName IN :programTypes AND IsActive = TRUE]){
            mapRecordTypes.put(rt.name,rt);    
        }

        List<Loyalty_Program_Setup__c> loyaltyProgramSetups = new List<Loyalty_Program_Setup__c>();

        for(Loyalty_Program__c loyaltyProgram : handler.getNewMap().values()){
            if(loyaltyProgram.Type__c != null && loyaltyProgram.Type__c != ''){
                String loyaltySetupType = loyaltyProgram.Type__c + ' Setup';

                Loyalty_Program_Setup__c newSetup = new Loyalty_Program_Setup__c();
                newSetup.RecordTypeId = mapRecordTypes.get(loyaltySetupType).id;
                newSetup.Loyalty_Program__c = loyaltyProgram.id;
                newSetup.Name = loyaltySetupType;
                newSetup.Active__c = true;

                loyaltyProgramSetups.add(newSetup);
            }
        }

        Database.SaveResult[] srSetups = Database.insert(loyaltyProgramSetups);


    }
}