LoyaltyApp/force-app/main/default/objects/Loyalty_Program__c/Loyalty_Program__c.object-meta.xml
<CustomObject>
    <label>Loyalty Program</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>TODAY() &gt;= Program_Start_Date__c  &amp;&amp; TODAY() &lt;= Program_End_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program__c/fields/Program_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Program_End_Date__c</fullName>
    <label>Program End Date</label>
    <type>Date</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program__c/fields/Program_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Program_Start_Date__c</fullName>
    <label>Program Start Date</label>
    <type>Date</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Card Program</fullName>
            </value>
            <value>
                <fullName>Hybrid Program</fullName>
            </value>
            <value>
                <fullName>Paid Program</fullName>
            </value>
            <value>
                <fullName>Partnered Program</fullName>
            </value>
            <value>
                <fullName>Point Program</fullName>
            </value>
            <value>
                <fullName>Spend Program</fullName>
            </value>
            <value>
                <fullName>Tiered Program</fullName>
            </value>
            <value>
                <fullName>Value Program</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup__c/Loyalty_Program_Setup__c.object-meta.xml
<CustomObject>
    <label>Loyalty Program Setup</label>
    <nameField>
        <label>Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Program Setups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup__c/fields/Loyalty_Program__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Program__c</fullName>
    <label>Loyalty Program</label>
    <referenceTo>Loyalty_Program__c</referenceTo>
    <relationshipLabel>Loyalty Program Setups</relationshipLabel>
    <relationshipName>Loyalty_Program_Setups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup__c/fields/Points_Per_Value_Spent__c.field-meta.xml
<CustomField>
    <fullName>Points_Per_Value_Spent__c</fullName>
    <label>Points Per Value Spent</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup__c/fields/Points_Validity_Days__c.field-meta.xml
<CustomField>
    <fullName>Points_Validity_Days__c</fullName>
    <label>Points Validity Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup__c/fields/Value_Spent__c.field-meta.xml
<CustomField>
    <fullName>Value_Spent__c</fullName>
    <label>Value Spent</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

LoyaltyApp/force-app/main/default/classes/Loyalty_Test_Ctrl_LoyaltyProgramSetup.cls
@isTest
private class Loyalty_Test_Ctrl_LoyaltyProgramSetup {
    @testSetup
    static void populateMockData() {List<Loyalty_Program__c> programs = new List<Loyalty_Program__c>();

        Loyalty_Program__c programPoints = new Loyalty_Program__c();
        programPoints.Type__c = 'Point Program';
        List<RecordType> pointRecordType = [Select Id From RecordType where sobjecttype = 'Loyalty_Program__c' and name = 'Point Program'];
        programPoints.RecordTypeId = pointRecordType[0].Id;
        programPoints.Program_Start_Date__c = system.today();
        programPoints.Program_End_Date__c = date.parse('27/12/2045');

        programs.add(programPoints);

        insert programs;

        Loyalty_Program_Setup__c pointsSetup = new Loyalty_Program_Setup__c();
        pointsSetup.Name = 'Point Program Setup';
        List<RecordType> pointSetupRecordType = [Select Id From RecordType where sobjecttype = 'Loyalty_Program_Setup__c' and name = 'Point Program Setup'];
        pointsSetup.RecordTypeId = pointSetupRecordType[0].Id;
        pointsSetup.Points_Per_Value_Spent__c = 23.0;
        pointsSetup.Value_Spent__c = 30.0;
        pointsSetup.Points_Validity_Days__c = 60.0;
        pointsSetup.Active__c = true;
        pointsSetup.Loyalty_Program__c = programPoints.Id;

        insert pointsSetup;
    }

    @isTest
    static void testGetProgramSetupId() {
        
        Test.startTest();
        List<Loyalty_Program__c> programs = [SELECT Id, Name FROM Loyalty_Program__c];
        
        Id programSetupId = Loyalty_Ctrl_LoyaltyProgramSetup.getProgramSetupId(programs[0].Id);
        System.assertNotEquals(programSetupId,null);

        Test.stopTest();
    }

    @isTest
    static void getProgramSetupRecordTypeId() {
        
        Test.startTest();
        List<Loyalty_Program__c> programs = [SELECT Id, Name FROM Loyalty_Program__c];
        
        Loyalty_Program_Setup__c programSetup = Loyalty_Ctrl_LoyaltyProgramSetup.getProgramSetupRecordTypeId(programs[0].Id);
        System.assertNotEquals(programSetup,null);

        Test.stopTest();

    }
}