LoyaltyApp/force-app/main/default/objects/Loyalty_Program__c/Loyalty_Program__c.object-meta.xml
<CustomObject>
    <label>Loyalty Program</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program__c/fields/Program_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Program_End_Date__c</fullName>
    <label>Program End Date</label>
    <type>Date</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program__c/fields/Program_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Program_Start_Date__c</fullName>
    <label>Program Start Date</label>
    <type>Date</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Card Program</fullName>
            </value>
            <value>
                <fullName>Hybrid Program</fullName>
            </value>
            <value>
                <fullName>Paid Program</fullName>
            </value>
            <value>
                <fullName>Partnered Program</fullName>
            </value>
            <value>
                <fullName>Point Program</fullName>
            </value>
            <value>
                <fullName>Spend Program</fullName>
            </value>
            <value>
                <fullName>Tiered Program</fullName>
            </value>
            <value>
                <fullName>Value Program</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup__c/Loyalty_Program_Setup__c.object-meta.xml
<CustomObject>
    <label>Loyalty Program Setup</label>
    <nameField>
        <label>Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Program Setups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup__c/fields/Loyalty_Program__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Program__c</fullName>
    <label>Loyalty Program</label>
    <referenceTo>Loyalty_Program__c</referenceTo>
    <relationshipLabel>Loyalty Program Setups</relationshipLabel>
    <relationshipName>Loyalty_Program_Setups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup__c/fields/Points_Per_Value_Spent__c.field-meta.xml
<CustomField>
    <fullName>Points_Per_Value_Spent__c</fullName>
    <label>Points Per Value Spent</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup__c/fields/Points_Validity_Days__c.field-meta.xml
<CustomField>
    <fullName>Points_Validity_Days__c</fullName>
    <label>Points Validity Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup__c/fields/Value_Spent__c.field-meta.xml
<CustomField>
    <fullName>Value_Spent__c</fullName>
    <label>Value Spent</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

LoyaltyApp/force-app/main/default/classes/Loyalty_Test_Util_ProgramSetupDml.cls
@isTest
private class Loyalty_Test_Util_ProgramSetupDml {
    private static Id testProgramId;
    private static Id testProgramSetupId;

    static void populateMockData() {
        List<Loyalty_Program__c> programs = new List<Loyalty_Program__c>();

        Loyalty_Program__c programPoints = new Loyalty_Program__c();
        programPoints.Type__c = 'Point Program';
        List<RecordType> pointRecordType = [Select Id From RecordType where sobjecttype = 'Loyalty_Program__c' and name = 'Point Program'];
        programPoints.RecordTypeId = pointRecordType[0].Id;
        programPoints.Program_Start_Date__c = system.today();
        programPoints.Program_End_Date__c = date.parse('27/12/2045');

        programs.add(programPoints);

        insert programs;

        testProgramId = programPoints.Id;

        List<Loyalty_Program_Setup__c> programSetups = new List<Loyalty_Program_Setup__c>();

        Loyalty_Program_Setup__c programPointsSetup = new Loyalty_Program_Setup__c();
        programPointsSetup.Loyalty_Program__c = programPoints.Id;
        List<RecordType> pointSetupRecordType = [Select Id From RecordType where sobjecttype = 'Loyalty_Program_Setup__c' and name = 'Point Program Setup'];
        programPointsSetup.RecordTypeId = pointSetupRecordType[0].Id;
        programPointsSetup.Points_Per_Value_Spent__c = 23;
        programPointsSetup.Value_Spent__c = 30;
        programPointsSetup.Points_Validity_Days__c = 60;

        programSetups.add(programPointsSetup);

        insert programSetups;

        testProgramSetupId = programPointsSetup.Id;
    }

    @IsTest static void testUtil_LoyaltyProgramSetupDml() {
    	Loyalty_Util_ProgramSetupDml controller = new Loyalty_Util_ProgramSetupDml();
    
    	System.assertNotEquals(controller,null); 
    }

    @IsTest static void testGetLoyaltyProgramSetupById() {
        Loyalty_Util_ProgramSetupDml controller = new Loyalty_Util_ProgramSetupDml();
        
        Test.startTest();
        populateMockData();
        Loyalty_Program_Setup__c programSetup = controller.getLoyaltyProgramSetupById(testProgramSetupId);
    
    	System.assertNotEquals(programSetup,null); 
        Test.stopTest();
    }

    @IsTest static void testGetLoyaltyProgramSetupByProgramId() {
        Loyalty_Util_ProgramSetupDml controller = new Loyalty_Util_ProgramSetupDml();
        
        Test.startTest();
        populateMockData();
        Loyalty_Program_Setup__c programSetup = controller.getLoyaltyProgramSetupByProgramId(testProgramId);
    
    	System.assertNotEquals(programSetup,null); 
        Test.stopTest();
    }

    @IsTest static void testGetLoyaltyProgramSetupByIdException() {
        Loyalty_Util_ProgramSetupDml controller = new Loyalty_Util_ProgramSetupDml();
        
        Test.startTest();
        populateMockData();
        try {
            Loyalty_Program_Setup__c programSetup = controller.getLoyaltyProgramSetupById('a032X00000VB2ccQAD');
            System.assertEquals(programSetup,null); 
        }
        catch(Exception ex) {
            System.assertNotEquals(ex,null);
        }
    
        Test.stopTest();
    }

    @IsTest static void testGetLoyaltyProgramSetupByProgramIdException() {
        Loyalty_Util_ProgramSetupDml controller = new Loyalty_Util_ProgramSetupDml();
        
        Test.startTest();
        populateMockData();
        try {
            Loyalty_Program_Setup__c programSetup = controller.getLoyaltyProgramSetupByProgramId('a002X00000ttFp1QAE');
            System.assertEquals(programSetup,null); 
        }
        catch(Exception ex) {
            System.assertNotEquals(ex,null);
        }
    
        Test.stopTest();
    }
}