LoyaltyApp/force-app/main/default/objects/Loyalty_Program__c/Loyalty_Program__c.object-meta.xml
<CustomObject>
    <label>Loyalty Program</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Card Program</fullName>
            </value>
            <value>
                <fullName>Hybrid Program</fullName>
            </value>
            <value>
                <fullName>Paid Program</fullName>
            </value>
            <value>
                <fullName>Partnered Program</fullName>
            </value>
            <value>
                <fullName>Point Program</fullName>
            </value>
            <value>
                <fullName>Spend Program</fullName>
            </value>
            <value>
                <fullName>Tiered Program</fullName>
            </value>
            <value>
                <fullName>Value Program</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Member__c/Loyalty_Program_Member__c.object-meta.xml
<CustomObject>
    <label>Loyalty Program Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Program Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Member__c/fields/Loyalty_Program__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Program__c</fullName>
    <label>Loyalty Program</label>
    <referenceTo>Loyalty_Program__c</referenceTo>
    <relationshipName>Program_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Member__c/fields/Member__c.field-meta.xml
<CustomField>
    <fullName>Member__c</fullName>
    <label>Member</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Program_Members</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

LoyaltyApp/force-app/main/default/classes/LoyaltyProgramMember_tl.cls
/*
   @Author: André Cunha
   @CreatedDate: 10/07/2020
   @Description: Loyalty program member trigger logic. Implemented methods with logic
 */
public class LoyaltyProgramMember_tl {
    private LoyaltyProgramMember_th handler;

    public LoyaltyProgramMember_tl(LoyaltyProgramMember_th handler) {
        this.handler = handler;
    }

    public void fillRecordTypeBasedOnProgram(){

        Set<String> programTypes = new Set<String>();
        Set<Id> programIds = new Set<Id>();
        
        for(Loyalty_Program_Member__c programMember : (List<Loyalty_Program_Member__c>)Trigger.new){
            if(programMember.Loyalty_Program__c != null){
                programIds.add(programMember.Loyalty_Program__c);    
            }
        }

        Map<Id,Loyalty_Program__c> programs = new Map<Id,Loyalty_Program__c>([SELECT id,Type__C FROM Loyalty_Program__c WHERE ID IN :programIds]);
        for(Loyalty_Program_Member__c programMember : (List<Loyalty_Program_Member__c>)Trigger.new){
            if(programs.containsKey(programMember.Loyalty_Program__c)){
                String loyaltyMemberType = programs.get(programMember.Loyalty_Program__c).Type__c + ' Member';
                programTypes.add(loyaltyMemberType.replaceAll(' ','_'));
            }
        }

        Map<String,RecordType> mapRecordTypes = new Map<String,RecordType>();

        for(RecordType rt : [SELECT id,Name,DeveloperName,SobjectType From RecordType WHERE DeveloperName IN :programTypes AND IsActive = TRUE]){
            mapRecordTypes.put(rt.name,rt);    
        }

        for(Loyalty_Program_Member__c programMember : (List<Loyalty_Program_Member__c>)Trigger.new){
            if(programs.containsKey(programMember.Loyalty_Program__c)){
                String loyaltyMemberType = programs.get(programMember.Loyalty_Program__c).Type__c + + ' Member';
                programMember.RecordTypeId = mapRecordTypes.get(loyaltyMemberType).id;
            }
		}
    }

    public void fillProgramMemberName(){
        
        Set<Id> accMemberIds = new Set<Id>();
        for(Loyalty_Program_Member__c programMember : (List<Loyalty_Program_Member__c>)Trigger.new){
            if(programMember.Member__c != null){
                accMemberIds.add(programMember.Member__c);    
            }
        }

        Map<Id,Account> members = new Map<Id,Account>([SELECT id,Name FROM Account WHERE ID IN :accMemberIds]);

        for(Loyalty_Program_Member__c programMember : (List<Loyalty_Program_Member__c>)Trigger.new){
            if(programMember.Member__c != null){
                programMember.Name = members.get(programMember.Member__c).Name;
            }
        }

    }
}