LoyaltyApp/force-app/main/default/objects/Loyalty_Program__c/Loyalty_Program__c.object-meta.xml
<CustomObject>
    <label>Loyalty Program</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>TODAY() &gt;= Program_Start_Date__c  &amp;&amp; TODAY() &lt;= Program_End_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup__c/Loyalty_Program_Setup__c.object-meta.xml
<CustomObject>
    <label>Loyalty Program Setup</label>
    <nameField>
        <label>Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Program Setups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup__c/fields/Loyalty_Program__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Program__c</fullName>
    <label>Loyalty Program</label>
    <referenceTo>Loyalty_Program__c</referenceTo>
    <relationshipLabel>Loyalty Program Setups</relationshipLabel>
    <relationshipName>Loyalty_Program_Setups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup__c/fields/Points_Per_Value_Spent__c.field-meta.xml
<CustomField>
    <fullName>Points_Per_Value_Spent__c</fullName>
    <label>Points Per Value Spent</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup_Rules__c/Loyalty_Program_Setup_Rules__c.object-meta.xml
<CustomObject>
    <label>Loyalty Program Setup Rule</label>
    <nameField>
        <label>Loyalty Program Setup Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Program Setup Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup_Rules__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>ISPICKVAL(Rule_Status__c, &apos;Active&apos;) = true &amp;&amp; (ISBLANK(Valid_From__c)=true || Valid_From__c &lt;=  TODAY()) &amp;&amp; (ISBLANK(Valid_To__c)=true || TODAY()&lt;= Valid_To__c)</formula>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup_Rules__c/fields/Assign_Points__c.field-meta.xml
<CustomField>
    <fullName>Assign_Points__c</fullName>
    <label>Assign Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup_Rules__c/fields/Assign_Points_Factor__c.field-meta.xml
<CustomField>
    <fullName>Assign_Points_Factor__c</fullName>
    <label>Assign Points Factor</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup_Rules__c/fields/Assign_Points_Factor_Operator__c.field-meta.xml
<CustomField>
    <fullName>Assign_Points_Factor_Operator__c</fullName>
    <label>Assign Points Factor Operator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Loyalty_Operator</valueSetName>
    </valueSet>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup_Rules__c/fields/Assign_Points_Factor_Type__c.field-meta.xml
<CustomField>
    <fullName>Assign_Points_Factor_Type__c</fullName>
    <label>Assign Points Factor Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Loyalty_Factor_Type</valueSetName>
    </valueSet>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup_Rules__c/fields/Assign_Points_Factor_Type_Value__c.field-meta.xml
<CustomField>
    <fullName>Assign_Points_Factor_Type_Value__c</fullName>
    <label>Assign Points Factor Type Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup_Rules__c/fields/Assign_Points_Field_Value_Name__c.field-meta.xml
<CustomField>
    <fullName>Assign_Points_Field_Value_Name__c</fullName>
    <label>Assign Points Field Value Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup_Rules__c/fields/Customer_Behaviour_Count__c.field-meta.xml
<CustomField>
    <fullName>Customer_Behaviour_Count__c</fullName>
    <label>Customer Behaviour Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup_Rules__c/fields/Customer_Behaviour_Factor__c.field-meta.xml
<CustomField>
    <fullName>Customer_Behaviour_Factor__c</fullName>
    <label>Customer Behaviour Factor</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup_Rules__c/fields/Loyalty_Program_Setup__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Program_Setup__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Loyalty Program Setup</label>
    <referenceTo>Loyalty_Program_Setup__c</referenceTo>
    <relationshipLabel>Loyalty Program Setup Rules</relationshipLabel>
    <relationshipName>Loyalty_Program_Setup_Rules</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup_Rules__c/fields/Object_Rules__c.field-meta.xml
<CustomField>
    <fullName>Object_Rules__c</fullName>
    <label>Object Rules</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup_Rules__c/fields/Rule_Status__c.field-meta.xml
<CustomField>
    <fullName>Rule_Status__c</fullName>
    <label>Rule Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Loyalty_Rule_Status</valueSetName>
    </valueSet>
</CustomField>

LoyaltyApp/force-app/main/default/globalValueSets/Loyalty_Factor_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Number of Purchases</fullName>
        <default>true</default>
        <label>Number of Purchases</label>
    </customValue>
    <customValue>
        <fullName>Field Value</fullName>
    </customValue>
    <customValue>
        <fullName>Products Quantity</fullName>
    </customValue>
    <masterLabel>Loyalty Factor Type</masterLabel>
</GlobalValueSet>

LoyaltyApp/force-app/main/default/globalValueSets/Loyalty_Operator.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>/</fullName>
    </customValue>
    <customValue>
        <fullName>*</fullName>
    </customValue>
    <customValue>
        <fullName>&gt;</fullName>
    </customValue>
    <customValue>
        <fullName>&lt;</fullName>
    </customValue>
    <customValue>
        <fullName>&gt;=</fullName>
    </customValue>
    <customValue>
        <fullName>&lt;=</fullName>
    </customValue>
    <customValue>
        <fullName>=</fullName>
    </customValue>
    <customValue>
        <fullName>!=</fullName>
    </customValue>
    <masterLabel>Loyalty Operator</masterLabel>
</GlobalValueSet>

LoyaltyApp/force-app/main/default/globalValueSets/Loyalty_Rule_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Review</fullName>
    </customValue>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Inactive</fullName>
    </customValue>
    <masterLabel>Loyalty Rule Status</masterLabel>
</GlobalValueSet>

LoyaltyApp/force-app/main/default/classes/Loyalty_Util_ProgramSetupRuleDml.cls
/*
   @Author: João Almeida
   @CreatedDate: 18/09/2020
   @Description: Contains the CRUD methods for Loyalty_Program_Setup_Rules__c SObject
 */
public with sharing class Loyalty_Util_ProgramSetupRuleDml extends Loyalty_Util_GenericDML {
    public class LoyaltyProgramSetupRuleException extends Exception {}
    
    public Loyalty_Util_ProgramSetupRuleDml() {
		    super('Loyalty_Program_Setup_Rules__c');
    }

    /*
	    @Description: gets the program setup rules by pagination definitions
      @param1: current page number
      @param2: page size - quantity of records per page
      @param3: used for infinite loaders instead of pagination
      @param4: defines if it is to get recently added data
      @param5: optional search keyword value
	    @Return: program setup rule records
	 */
	  public List<Loyalty_Program_Setup_Rules__c> getProgramSetupRules(Integer pagenumber, Integer pageSize, Integer lastRecordPosition, Boolean isAddedData, String searchString) {
        List<Loyalty_Program_Setup_Rules__c> programSetupRules = null;
        try {
            List<String> orderBy = new List<String> {'Name'};
            // deal with offset of an infinite loader
            integer newOffset= pageSize;
            integer newPageNumber= pagenumber;
            Integer newPageSize = (lastRecordPosition == null ? 0 : lastRecordPosition) - pageSize;
            if (newPageSize > 0) {
                newOffset = ((pagenumber * pageSize) + newPageSize) - pageSize;
                newPageNumber = 2;
                if (isAddedData == true) {
                    orderBy = new List<String> {'Id'};
                }
            }

            List<String> selectableFields = new List<String> {'Id','Name', 'Active__c', 'Rule_Status__c', 'Loyalty_Program_Setup__c', 'Loyalty_Program_Setup__r.Loyalty_Program__c',
                                                               'Loyalty_Program_Setup__r.Loyalty_Program__r.Name', 'Loyalty_Program_Setup__r.Points_Per_Value_Spent__c',
                                                                'Assign_Points__c','Assign_Points_Factor__c','Assign_Points_Factor_Operator__c', 'Assign_Points_Factor_Type__c', 'Object_Rules__c',
                                                                'Assign_Points_Factor_Type_Value__c', 'Assign_Points_Field_Value_Name__c', 'Customer_Behaviour_Count__c', 'Customer_Behaviour_Factor__c',
                                                                'Valid_From__c', 'Valid_To__c'};
            
            programSetupRules = (Loyalty_Program_Setup_Rules__c[])this.selectRecords(newPageNumber, newOffset, searchString, null, selectableFields,null, orderBy, null, false, false);
        }
        catch (Exception ex) {
            throw ex;
        }

        return programSetupRules;
    }

    /*
	  @Description: get the program setup rule by id
      @param1: setup rule id
	  @Return: program setup rule record
	 */
	  public Loyalty_Program_Setup_Rules__c getProgramSetupRuleById(Id setupRuleId) {
        Loyalty_Program_Setup_Rules__c programSetupRule = null;
        try {
            List<Loyalty_Program_Setup_Rules__c> setupRules = (Loyalty_Program_Setup_Rules__c[])this.selectById(setupRuleId,null, false, false);
            if (!setupRules.isEmpty()) {
                if (setupRules.size() == 1) {
                    programSetupRule = setupRules[0];
                }
                else {
                    throw new LoyaltyProgramSetupRuleException('getProgramSetupRuleById Error: ' + 'more than 1 setup rule found for Id ' + setupRuleId);
                }
            }
            else {
                throw new LoyaltyProgramSetupRuleException('getProgramSetupRuleById Error: ' + 'no setup rule found for Id ' + setupRuleId);
            }
        }
        catch (Exception ex) {
            throw ex;
        }

        return programSetupRule;
    }

    /*
	  @Description: gets the program setup rules by program setup id
      @param1: program setup id
      @param2: active rules
	  @Return: program setup rule records
	 */
	  public List<Loyalty_Program_Setup_Rules__c> getProgramSetupRulesByProgramSetupId(Id programSetupId, boolean activeRules) {
        List<Loyalty_Program_Setup_Rules__c> programSetupRules = null;
        try {
            List<String> selectableFields = new List<String> {'Id','Name', 'Active__c', 'Rule_Status__c', 'Assign_Points__c', 'Assign_Points_Factor__c', 'Loyalty_Program_Setup__c',
                                                               'Customer_Behaviour_Count__c', 'Customer_Behaviour_Factor__c', 'Object_Rules__c', 'Valid_From__c', 'Valid_To__c',
                                                                'Assign_Points_Factor_Operator__c', 'Assign_Points_Factor_Type__c', 'Assign_Points_Factor_Type_Value__c', 'Assign_Points_Field_Value_Name__c'};
            List<String> orderBy = new List<String> {'Name'};
            List<String> whereClauses = new List<String>{ 'Loyalty_Program_Setup__c=\'' + programSetupId + '\'', 'and Active__c=' + activeRules };
            programSetupRules = (Loyalty_Program_Setup_Rules__c[])this.selectRecords(0, 0, null, null, selectableFields,whereClauses, orderBy, null, false, false);
        }
        catch (Exception ex) {
            throw ex;
        }

        return programSetupRules;
    }
    
    /*
      @Description: gets the list views related to Loyalty_Program_Setup_Rule__c SObject
      @Return: the list of listViews
	 */
    public List<ListView> getLoyaltyProgramSetupRuleListViews() {
        List<ListView> programSetupRuleListViews = [SELECT Id, DeveloperName, Name FROM ListView WHERE SObjectType = 'Loyalty_Program_Setup_Rule__c'];

        return programSetupRuleListViews;
    }

    /*
      @Description: gets the cont of Loyalty_Program_Setup_Rule__c SObject
      @Return: the count
	 */
    public integer getLoyaltyProgramSetupRulesCount() {
        integer quantity = this.count(null, null, false, false);

        return quantity;
    }

    /*
      @Description: gets the list of fields related to Loyalty_Program_Setup_Rule__c SObject
      @Return: the list of fields
	 */
    public List<Loyalty_Util_GenericDML.GenericFieldMapper> getLoyaltyProgramSetupRuleFieldsList() {
        List<Loyalty_Util_GenericDML.GenericFieldMapper> fields = this.getSObjectFieldsList();

        return fields;
    }

    /*
      @Description: inserts a new Program Setup Rule on database
      @param1: the record to insert
      @Return: the result message
	 */
    public string insertProgramSetupRule(Loyalty_Program_Setup_Rules__c newSetupBonusRule) {
        List<Loyalty_Program_Setup_Rules__c> toInsert = new List<Loyalty_Program_Setup_Rules__c>();
        toInsert.add(newSetupBonusRule);
        string result = this.insertBulk(toInsert);
        if (result != 'INSERT SUCCESS') {
            throw new LoyaltyProgramSetupRuleException('insertProgramSetupRule error: ' + result);
        }
        return result;
    }

    /*
      @Description: updates a Program Setup Rule on database
      @param1: the record to update
      @Return: the result message
	 */
    public string updateProgramSetupRule(Loyalty_Program_Setup_Rules__c editSetupBonusRule) {
        List<Loyalty_Program_Setup_Rules__c> toUpdate = new List<Loyalty_Program_Setup_Rules__c>();
        toUpdate.add(editSetupBonusRule);
        string result = this.updateBulk(toUpdate);
        if (result != 'UPDATE SUCCESS') {
            throw new LoyaltyProgramSetupRuleException('updateProgramSetupRule error: ' + result);
        }
        return result;
    }
}