LoyaltyApp/force-app/main/default/objects/Loyalty_Level__c/Loyalty_Level__c.object-meta.xml
<CustomObject>
    <label>Loyalty Level</label>
    <nameField>
        <label>Loyalty Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Levels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program__c/Loyalty_Program__c.object-meta.xml
<CustomObject>
    <label>Loyalty Program</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>TODAY() &gt;= Program_Start_Date__c  &amp;&amp; TODAY() &lt;= Program_End_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program__c/fields/Program_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Program_End_Date__c</fullName>
    <label>Program End Date</label>
    <type>Date</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program__c/fields/Program_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Program_Start_Date__c</fullName>
    <label>Program Start Date</label>
    <type>Date</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Card Program</fullName>
            </value>
            <value>
                <fullName>Hybrid Program</fullName>
            </value>
            <value>
                <fullName>Paid Program</fullName>
            </value>
            <value>
                <fullName>Partnered Program</fullName>
            </value>
            <value>
                <fullName>Point Program</fullName>
            </value>
            <value>
                <fullName>Spend Program</fullName>
            </value>
            <value>
                <fullName>Tiered Program</fullName>
            </value>
            <value>
                <fullName>Value Program</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Member__c/Loyalty_Program_Member__c.object-meta.xml
<CustomObject>
    <label>Loyalty Program Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Program Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Member__c/fields/Loyalty_Level__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Level__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Loyalty Level</label>
    <referenceTo>Loyalty_Level__c</referenceTo>
    <relationshipName>Program_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Member__c/fields/Loyalty_Program__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Program__c</fullName>
    <label>Loyalty Program</label>
    <referenceTo>Loyalty_Program__c</referenceTo>
    <relationshipName>Program_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Member__c/fields/Member__c.field-meta.xml
<CustomField>
    <fullName>Member__c</fullName>
    <label>Member</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Program_Members</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Member__c/fields/Member_Number__c.field-meta.xml
<CustomField>
    <fullName>Member_Number__c</fullName>
    <label>Member Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

LoyaltyApp/force-app/main/default/classes/Loyalty_Util_ProgramMemberDml.cls
/*
   @Author: João Almeida
   @CreatedDate: 11/09/2020
   @Description: Contains the CRUD methods for Loyalty_Program_Member__c SObject
 */
public with sharing class Loyalty_Util_ProgramMemberDml extends Loyalty_Util_GenericDML {
	private class LoyaltyProgramMemberDmlException extends Exception {}

	public Loyalty_Util_ProgramMemberDml() {
		super('Loyalty_Program_Member__c');
	}

	/*
	   @Description: gets program members records by account ID
	   @param1: account ID
	   @Return: the programs records related to the account ID
	   @Exception: thrown when there is no record related
	 */
	public List<Loyalty_Program_Member__c> getCustomerLoyaltyProgramsByAccountId(Id accountId) {
		List<Loyalty_Program_Member__c> programs = null;
		try {
			List<String> selectableFields = new List<String> {'Id','Member_Number__c', 'Member__r.Loyalty_Opportunity_Total_of_Purchases__c', 'Member__r.Loyalty_Oppty_Bought_Items_Quantity__c', 'Loyalty_Program__r.Id', 'Loyalty_Program__r.Type__c', 'Loyalty_Program__r.Program_Start_Date__c', 'Loyalty_Program__r.Program_End_Date__c'};
			List<String> orderBy = new List<String> {'Joining_Date__c'};
			List<String> whereClauses = new List<String> {'Member__c=\'' + accountId +'\'', 'and Loyalty_Program__r.Active__c=true'};
			programs = (Loyalty_Program_Member__c[])this.selectRecords(0, 0, null, null, selectableFields,whereClauses, orderBy, null, false, false);
			if (programs.isEmpty()) {
				throw new LoyaltyProgramMemberDmlException('getCustomerLoyaltyProgramsByAccountId Error: ' + 'no program member found for account Id ' + accountId);
			}
		}
		catch (Exception ex) {
			throw ex;
		}

		return programs;
	}

	/*
	   @Description: gets the member program types by account ID
	   @param1: account ID
	   @Return: the program types related to the account ID
	   @Exception: thrown when there is no record related
	 */
	public Set<String> getCustomerLoyaltyProgramTypesByAccountId(Id accountId) {
		Set<String> programTypes = new Set<String>();
		try {
			List<String> selectableFields = new List<String> {'Loyalty_Program__r.Type__c'};
			List<String> orderBy = new List<String> {'Joining_Date__c'};
			List<String> whereClauses = new List<String> {'Member__c=\'' + accountId +'\'', 'and Loyalty_Program__r.Active__c=true'};
			List<Loyalty_Program_Member__c> programs = (Loyalty_Program_Member__c[])this.selectRecords(1, 1, null, null, selectableFields,whereClauses, orderBy, null, false, false);
			if (programs.isEmpty()) {
				throw new LoyaltyProgramMemberDmlException('getCustomerLoyaltyProgramTypesByAccountId Error: ' + 'no program member found for account Id ' + accountId);
			}
			else {
				for (Loyalty_Program_Member__c member : programs) {
					programTypes.add(member.Loyalty_Program__r.Type__c);
				}
			}
		}
		catch (Exception ex) {
			throw ex;
		}

		return programTypes;
	}
	
	/*
	   @Description: gets the current loyalty level of the customer by account ID and loyalty program ID
	   @param1: account ID
	   @param2: loyalty program ID
	   @Return: the current loyalty level related to the account ID
	   @Exception: thrown when there is no record related
	 */
	public Loyalty_Program_Member__c getCurrentCustomerLoyaltyLevel(Id accountId, Id programId) {
		Loyalty_Program_Member__c programMemberLevel = null;
		try {
			List<String> selectableFields = new List<String> {'Id','Member_Number__c', 'Member__r.Loyalty_Opportunity_Total_of_Purchases__c', 'Member__r.Loyalty_Oppty_Bought_Items_Quantity__c', 'Loyalty_Level__r.Id', 'Loyalty_Level__r.Name'};
			List<String> orderBy = new List<String> {'Joining_Date__c'};
			List<String> whereClauses = new List<String> {'Member__c=\'' + accountId +'\'', 'and Is_Active__c=true'};
			if (programId != null && !String.isEmpty(programId)) {
				whereClauses.add('and Loyalty_Program__c=\'' + programId +'\'');
			}
			List<Loyalty_Program_Member__c> programs = (Loyalty_Program_Member__c[])this.selectRecords(0, 0, null, null, selectableFields,whereClauses, orderBy, null, false, false);
			if (programs != null && !programs.isEmpty()) {
				programMemberLevel = programs[0];
			}
			else {
				throw new LoyaltyProgramMemberDmlException('getCurrentCustomerLoyaltyLevel Error: ' + 'no program member found for account Id ' + accountId);
			}
		}
		catch (Exception ex) {
			throw ex;
		}

		return programMemberLevel;
	}

	/*
	   @Description: updates Program Member records
	   @param1: the updated Program Member records
	   @Return: the result message 'UPDATE SUCCESS' if success, any other else
	 */
	public string updateCustomerProgramMembers(List<Loyalty_Program_Member__c> updatedValues) {
		string resultMessage;
		if (updatedValues != null && !updatedValues.isEmpty()) {
			resultMessage = this.updateBulk(updatedValues);
        }
        else {
            resultMessage = 'The list of Loyalty_Program_Member__c must contain records to be updated';
        }

        return resultMessage;
	}
}