LoyaltyApp/force-app/main/default/objects/Loyalty_Level__c/Loyalty_Level__c.object-meta.xml
<CustomObject>
    <label>Loyalty Level</label>
    <nameField>
        <label>Loyalty Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Levels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Member__c/Loyalty_Program_Member__c.object-meta.xml
<CustomObject>
    <label>Loyalty Program Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Program Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Member__c/fields/Loyalty_Level__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Level__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Loyalty Level</label>
    <referenceTo>Loyalty_Level__c</referenceTo>
    <relationshipName>Program_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup__c/Loyalty_Program_Setup__c.object-meta.xml
<CustomObject>
    <label>Loyalty Program Setup</label>
    <nameField>
        <label>Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Program Setups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup_Level__c/Loyalty_Program_Setup_Level__c.object-meta.xml
<CustomObject>
    <label>Loyalty Program Setup Level</label>
    <nameField>
        <label>Program Setup Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Program Setup Levels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup_Level__c/fields/Achievable_Bought_Items__c.field-meta.xml
<CustomField>
    <fullName>Achievable_Bought_Items__c</fullName>
    <description>Quantity of items bought in order to achieve the loyalty level</description>
    <label>Achievable Bought Items</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup_Level__c/fields/Achievable_Points__c.field-meta.xml
<CustomField>
    <fullName>Achievable_Points__c</fullName>
    <description>Points to reach in order to get the loyalty level</description>
    <label>Achievable Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup_Level__c/fields/Achievable_Purchases__c.field-meta.xml
<CustomField>
    <fullName>Achievable_Purchases__c</fullName>
    <description>number of purchases in order to achieve loyalty level</description>
    <label>Achievable Purchases</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup_Level__c/fields/Is_Bought_Items_Mandatory__c.field-meta.xml
<CustomField>
    <fullName>Is_Bought_Items_Mandatory__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Defines if the quantity of bought items is mandatory to achieve the loyalty level</description>
    <inlineHelpText>Defines if the quantity of bought items is mandatory to achieve the loyalty level</inlineHelpText>
    <label>Is Bought Items Mandatory</label>
    <type>Checkbox</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup_Level__c/fields/Is_Points_Manadatory__c.field-meta.xml
<CustomField>
    <fullName>Is_Points_Manadatory__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Defines if the quantity of points is mandatory to achieve the loyalty level</description>
    <inlineHelpText>Defines if the quantity of points is mandatory to achieve the loyalty level</inlineHelpText>
    <label>Is Number of Points Manadatory</label>
    <type>Checkbox</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup_Level__c/fields/Is_Purchases_Mandatory__c.field-meta.xml
<CustomField>
    <fullName>Is_Purchases_Mandatory__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Defines if the quantity of purchases is mandatory to achieve the loyalty level</description>
    <inlineHelpText>Defines if the quantity of purchases is mandatory to achieve the loyalty level</inlineHelpText>
    <label>Is Purchases Mandatory</label>
    <type>Checkbox</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup_Level__c/fields/Loyalty_Level__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Level__c</fullName>
    <label>Loyalty Level</label>
    <referenceTo>Loyalty_Level__c</referenceTo>
    <relationshipName>Program_Setup_Levels</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup_Level__c/fields/Loyalty_Program_Setup__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Program_Setup__c</fullName>
    <label>Loyalty Program Setup</label>
    <referenceTo>Loyalty_Program_Setup__c</referenceTo>
    <relationshipName>Program_Setup_Levels</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

LoyaltyApp/force-app/main/default/classes/Loyalty_Util_ManageLevels.cls
public with sharing class Loyalty_Util_ManageLevels implements Loyalty_I_ManageLevels {
    public Loyalty_Util_ManageLevels() {

    }

    /*
	   @Description: determines if the customer can achieve a new loyalty level
       @param1: the customer spend points if any
       @param2: the customer total bought items if any
       @param3: the customer total purchases if any
       @param4: the customer account id
       @param5: the customer loyalty program setup record
       @param6: the customer program member record
	   @Return: the new level if reached, null otherwise
	 */
    public Loyalty_Program_Setup_Level__c calculateNewCustomerLoyaltyLevel(integer customerTotalSpendPoints, integer customerTotalBoughtItems, integer customerTotalPurchases, Id accountId, Loyalty_Program_Setup__c programSetup, Loyalty_Program_Member__c customerProgramMember) {
        Loyalty_Program_Setup_Level__c nextLevelReached = null;
        Loyalty_Program_Setup_Level__c memberLevelSetup = null;
        List<Loyalty_Program_Setup_Level__c> programSetupLevels = null;
        Loyalty_Util_ProgramSetupLevelDml programSetupLevelDml = new Loyalty_Util_ProgramSetupLevelDml();

        try {
            if (customerProgramMember != null && customerProgramMember.Loyalty_Level__c != null) {
                memberLevelSetup = programSetupLevelDml.getProgramSetupLevelByLoyaltyLevelId(customerProgramMember.Loyalty_Level__r.Id);
            }

            programSetupLevels = programSetupLevelDml.getNextProgramSetupLevels(programSetup.Id, memberLevelSetup);
        }
        catch(Exception ex) {

        }

        for (Loyalty_Program_Setup_Level__c setupLevel : programSetupLevels) {
			boolean boughtItemsAchieved = true;
			boolean pointsAchieved = true;
            boolean numPurchasesAchieved = true;
            System.debug(customerTotalSpendPoints + ' achievable points: ' + setupLevel.Achievable_Points__c);
            System.debug(customerTotalBoughtItems + ' achievable bought items: ' + setupLevel.Achievable_Bought_Items__c);
            System.debug(customerTotalPurchases + ' achievable purchases: ' + setupLevel.Achievable_Purchases__c);
			if (setupLevel.Is_Bought_Items_Mandatory__c) {
				if (customerTotalBoughtItems < setupLevel.Achievable_Bought_Items__c
					|| (nextLevelReached != null && nextLevelReached.Is_Bought_Items_Mandatory__c && nextLevelReached.Achievable_Bought_Items__c > setupLevel.Achievable_Bought_Items__c)
					) {
					boughtItemsAchieved = false;
				}
			}
			if (setupLevel.Is_Points_Manadatory__c) {
				if (customerTotalSpendPoints < setupLevel.Achievable_Points__c
					|| (nextLevelReached != null && nextLevelReached.Is_Points_Manadatory__c && nextLevelReached.Achievable_Points__c > setupLevel.Achievable_Points__c)
					) {
					pointsAchieved = false;
				}
			}
			if (setupLevel.Is_Purchases_Mandatory__c) {
				if (customerTotalPurchases < setupLevel.Achievable_Purchases__c
					|| (nextLevelReached != null && nextLevelReached.Is_Purchases_Mandatory__c && nextLevelReached.Achievable_Purchases__c > setupLevel.Achievable_Purchases__c)
					) {
					numPurchasesAchieved = false;
				}
			}
			System.debug(boughtItemsAchieved);
			System.debug(pointsAchieved);
			System.debug(numPurchasesAchieved);
			System.debug(customerTotalPurchases);
			if (boughtItemsAchieved && pointsAchieved && numPurchasesAchieved) {
				nextLevelReached = setupLevel;
			}
		}
		System.debug('levelreached: ');
        System.debug(nextLevelReached);
        
        return nextLevelReached;
    }
}