LoyaltyApp/force-app/main/default/objects/Loyalty_Level__c/Loyalty_Level__c.object-meta.xml
<CustomObject>
    <label>Loyalty Level</label>
    <nameField>
        <label>Loyalty Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Levels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program__c/Loyalty_Program__c.object-meta.xml
<CustomObject>
    <label>Loyalty Program</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program__c/fields/Program_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Program_End_Date__c</fullName>
    <label>Program End Date</label>
    <type>Date</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program__c/fields/Program_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Program_Start_Date__c</fullName>
    <label>Program Start Date</label>
    <type>Date</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Card Program</fullName>
            </value>
            <value>
                <fullName>Hybrid Program</fullName>
            </value>
            <value>
                <fullName>Paid Program</fullName>
            </value>
            <value>
                <fullName>Partnered Program</fullName>
            </value>
            <value>
                <fullName>Point Program</fullName>
            </value>
            <value>
                <fullName>Spend Program</fullName>
            </value>
            <value>
                <fullName>Tiered Program</fullName>
            </value>
            <value>
                <fullName>Value Program</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Member__c/Loyalty_Program_Member__c.object-meta.xml
<CustomObject>
    <label>Loyalty Program Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Program Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Member__c/fields/Loyalty_Level__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Level__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Loyalty Level</label>
    <referenceTo>Loyalty_Level__c</referenceTo>
    <relationshipName>Program_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Member__c/fields/Loyalty_Program__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Program__c</fullName>
    <label>Loyalty Program</label>
    <referenceTo>Loyalty_Program__c</referenceTo>
    <relationshipName>Program_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Member__c/fields/Member__c.field-meta.xml
<CustomField>
    <fullName>Member__c</fullName>
    <label>Member</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Program_Members</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Member__c/fields/Member_Number__c.field-meta.xml
<CustomField>
    <fullName>Member_Number__c</fullName>
    <label>Member Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup__c/Loyalty_Program_Setup__c.object-meta.xml
<CustomObject>
    <label>Loyalty Program Setup</label>
    <nameField>
        <label>Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Program Setups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup__c/fields/Loyalty_Program__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Program__c</fullName>
    <label>Loyalty Program</label>
    <referenceTo>Loyalty_Program__c</referenceTo>
    <relationshipLabel>Loyalty Program Setups</relationshipLabel>
    <relationshipName>Loyalty_Program_Setups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup__c/fields/Points_Per_Value_Spent__c.field-meta.xml
<CustomField>
    <fullName>Points_Per_Value_Spent__c</fullName>
    <label>Points Per Value Spent</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup__c/fields/Points_Validity_Days__c.field-meta.xml
<CustomField>
    <fullName>Points_Validity_Days__c</fullName>
    <label>Points Validity Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup__c/fields/Value_Spent__c.field-meta.xml
<CustomField>
    <fullName>Value_Spent__c</fullName>
    <label>Value Spent</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup_Level__c/Loyalty_Program_Setup_Level__c.object-meta.xml
<CustomObject>
    <label>Loyalty Program Setup Level</label>
    <nameField>
        <label>Program Setup Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Program Setup Levels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup_Level__c/fields/Achievable_Bought_Items__c.field-meta.xml
<CustomField>
    <fullName>Achievable_Bought_Items__c</fullName>
    <description>Quantity of items bought in order to achieve the loyalty level</description>
    <label>Achievable Bought Items</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup_Level__c/fields/Achievable_Points__c.field-meta.xml
<CustomField>
    <fullName>Achievable_Points__c</fullName>
    <description>Points to reach in order to get the loyalty level</description>
    <label>Achievable Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup_Level__c/fields/Achievable_Purchases__c.field-meta.xml
<CustomField>
    <fullName>Achievable_Purchases__c</fullName>
    <description>number of purchases in order to achieve loyalty level</description>
    <label>Achievable Purchases</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup_Level__c/fields/Is_Bought_Items_Mandatory__c.field-meta.xml
<CustomField>
    <fullName>Is_Bought_Items_Mandatory__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Defines if the quantity of bought items is mandatory to achieve the loyalty level</description>
    <inlineHelpText>Defines if the quantity of bought items is mandatory to achieve the loyalty level</inlineHelpText>
    <label>Is Bought Items Mandatory</label>
    <type>Checkbox</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup_Level__c/fields/Is_Points_Manadatory__c.field-meta.xml
<CustomField>
    <fullName>Is_Points_Manadatory__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Defines if the quantity of points is mandatory to achieve the loyalty level</description>
    <inlineHelpText>Defines if the quantity of points is mandatory to achieve the loyalty level</inlineHelpText>
    <label>Is Number of Points Manadatory</label>
    <type>Checkbox</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup_Level__c/fields/Is_Purchases_Mandatory__c.field-meta.xml
<CustomField>
    <fullName>Is_Purchases_Mandatory__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Defines if the quantity of purchases is mandatory to achieve the loyalty level</description>
    <inlineHelpText>Defines if the quantity of purchases is mandatory to achieve the loyalty level</inlineHelpText>
    <label>Is Purchases Mandatory</label>
    <type>Checkbox</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup_Level__c/fields/Loyalty_Level__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Level__c</fullName>
    <label>Loyalty Level</label>
    <referenceTo>Loyalty_Level__c</referenceTo>
    <relationshipName>Program_Setup_Levels</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup_Level__c/fields/Loyalty_Program_Setup__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Program_Setup__c</fullName>
    <label>Loyalty Program Setup</label>
    <referenceTo>Loyalty_Program_Setup__c</referenceTo>
    <relationshipName>Program_Setup_Levels</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Program_Setup_Level__c/fields/Loyalty_Reward_Achievable__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Reward_Achievable__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A possible reward for when the customer reaches the loyalty level</description>
    <label>Loyalty Reward Achievable</label>
    <referenceTo>Loyalty_Reward__c</referenceTo>
    <relationshipName>Program_Setup_Levels</relationshipName>
    <type>Lookup</type>
</CustomField>

LoyaltyApp/force-app/main/default/classes/Loyalty_Test_Util_ProgramSetupLevelDml.cls
@isTest
private class Loyalty_Test_Util_ProgramSetupLevelDml {
    private static Id accountId;
    private static Id programSetupId;
    private static Id loyaltyLevelId;
    private static Loyalty_Program_Setup_Level__c currentLevel;

    @testSetup
    static void populateMockData() {
        Account a = new Account(Name = 'Test Account');
        insert a;

        accountId = a.Id;

        List<Loyalty_Program__c> programs = new List<Loyalty_Program__c>();

        Loyalty_Program__c programSpend = new Loyalty_Program__c();
        programSpend.Type__c = 'Spend Program';
        List<RecordType> spendRecordType = [Select Id From RecordType where sobjecttype = 'Loyalty_Program__c' and name = 'Spend Program'];
        programSpend.RecordTypeId = spendRecordType[0].Id;
        programSpend.Program_Start_Date__c = system.today();
        programSpend.Program_End_Date__c = date.parse('27/12/2045');

        programs.add(programSpend);

        insert programs;
        
        Loyalty_Level__c loyaltyLevel = new Loyalty_Level__c();
		loyaltyLevel.Name = 'Silver Customer';

        insert loyaltyLevel;
        
        Loyalty_Level__c loyaltyLevel2 = new Loyalty_Level__c();
		loyaltyLevel2.Name = 'Gold Customer';

        insert loyaltyLevel2;

        loyaltyLevelId = loyaltyLevel.Id;

        List<Loyalty_Program_Member__c> members = new List<Loyalty_Program_Member__c>();
        
        Loyalty_Program_Member__c member = new Loyalty_Program_Member__c();
        member.Name = 'Silver Customer';
        member.Is_Active__c = true;
        member.Joining_Date__c = date.today();
        member.Loyalty_Level__c = loyaltyLevel.Id;
        member.Loyalty_Program__c = programSpend.Id;
        member.Member__c = a.Id;
        member.Member_Number__c = 'FIRSTMEMBER0001';
        spendRecordType = [Select Id From RecordType where sobjecttype = 'Loyalty_Program_Member__c' and name = 'Spend Program Member'];
        member.RecordTypeId = spendRecordType[0].Id;
        
        members.add(member);

        insert members;
        
        List<Loyalty_Program_Setup__c> programSetups = new List<Loyalty_Program_Setup__c>();

        Loyalty_Program_Setup__c programSpendSetup = new Loyalty_Program_Setup__c();
        programSpendSetup.Loyalty_Program__c = programSpend.Id;
        List<RecordType> spendSetupRecordType = [Select Id From RecordType where sobjecttype = 'Loyalty_Program_Setup__c' and name = 'Spend Program Setup'];
        programSpendSetup.RecordTypeId = spendSetupRecordType[0].Id;
        programSpendSetup.Points_Per_Value_Spent__c = 23;
        programSpendSetup.Value_Spent__c = 30;
        programSpendSetup.Points_Validity_Days__c = 600;

        programSetups.add(programSpendSetup);

        insert programSetups;

        programSetupId = programSpendSetup.Id;
        
        List<Loyalty_Program_Setup_Level__c> programSetupLevels = new List<Loyalty_Program_Setup_Level__c>();

        Loyalty_Program_Setup_Level__c programSpendSetupLevel = new Loyalty_Program_Setup_Level__c();
        programSpendSetupLevel.Achievable_Bought_Items__c = 4;
        programSpendSetupLevel.Achievable_Points__c = 50;
        programSpendSetupLevel.Achievable_Purchases__c = 5;
        programSpendSetupLevel.Is_Bought_Items_Mandatory__c = false;
        programSpendSetupLevel.Is_Points_Manadatory__c = true;
        programSpendSetupLevel.Is_Purchases_Mandatory__c = false;
        programSpendSetupLevel.Loyalty_Level__c = loyaltyLevel.Id;
        programSpendSetupLevel.Loyalty_Program_Setup__c = programSpendSetup.Id;
        programSpendSetupLevel.Loyalty_Reward_Achievable__c = null;
        programSpendSetupLevel.Name = 'Spend silver level';

        programSetupLevels.add(programSpendSetupLevel);

        
        Loyalty_Program_Setup_Level__c programSpendSetupLevel2 = new Loyalty_Program_Setup_Level__c();
        programSpendSetupLevel2.Achievable_Bought_Items__c = 40;
        programSpendSetupLevel2.Achievable_Points__c = 500;
        programSpendSetupLevel2.Achievable_Purchases__c = 50;
        programSpendSetupLevel2.Is_Bought_Items_Mandatory__c = true;
        programSpendSetupLevel2.Is_Points_Manadatory__c = true;
        programSpendSetupLevel2.Is_Purchases_Mandatory__c = false;
        programSpendSetupLevel2.Loyalty_Level__c = loyaltyLevel2.Id;
        programSpendSetupLevel2.Loyalty_Program_Setup__c = programSpendSetup.Id;
        programSpendSetupLevel2.Loyalty_Reward_Achievable__c = null;
        programSpendSetupLevel2.Name = 'Spend Gold level';

        programSetupLevels.add(programSpendSetupLevel2);

        insert programSetupLevels;

        currentLevel = programSpendSetupLevel;
    }

    @IsTest static void testUtil_ProgramSetupLevelDml() {
    	Loyalty_Util_ProgramSetupLevelDml controller = new Loyalty_Util_ProgramSetupLevelDml();
    
    	System.assertNotEquals(controller,null); 
    }

    @IsTest static void testGetProgramSetupLevelsByProgramSetupId() {
        Loyalty_Util_ProgramSetupLevelDml controller = new Loyalty_Util_ProgramSetupLevelDml();
        
        Test.startTest();
        populateMockData();
        List<Loyalty_Program_Setup_Level__c> programSetupLevels = controller.getProgramSetupLevelsByProgramSetupId(programSetupId);
    
    	System.assertNotEquals(programSetupLevels,null); 
        Test.stopTest();
    }

    @IsTest static void testGetProgramSetupLevelByLoyaltyLevelId() {
        Loyalty_Util_ProgramSetupLevelDml controller = new Loyalty_Util_ProgramSetupLevelDml();
        
        Test.startTest();
        populateMockData();
        Loyalty_Program_Setup_Level__c programSetupLevel = controller.getProgramSetupLevelByLoyaltyLevelId(loyaltyLevelId);
    
    	System.assertNotEquals(programSetupLevel,null); 
        Test.stopTest();
    }

    @IsTest static void testGetNextProgramSetupLevels() {
        Loyalty_Util_ProgramSetupLevelDml controller = new Loyalty_Util_ProgramSetupLevelDml();
        
        Test.startTest();
        populateMockData();
        List<Loyalty_Program_Setup_Level__c> programSetupLevels = controller.getNextProgramSetupLevels(programSetupId, currentLevel);
    
    	System.assertNotEquals(programSetupLevels,null); 
        Test.stopTest();
    }
}