LoyaltyApp/force-app/main/default/objects/Loyalty_Member_Bonus__c/Loyalty_Member_Bonus__c.object-meta.xml
<CustomObject>
    <label>Loyalty Member Bonus</label>
    <nameField>
        <displayFormat>MB{0000000000}</displayFormat>
        <label>Loyalty Member Bonus Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loyalty Member Bonuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LoyaltyApp/force-app/main/default/objects/Loyalty_Member_Bonus__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loyalty Member Bonuses</relationshipLabel>
    <relationshipName>Loyalty_Member_Bonuses</relationshipName>
    <type>Lookup</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Member_Bonus__c/fields/Bonus_Assigned_Date__c.field-meta.xml
<CustomField>
    <fullName>Bonus_Assigned_Date__c</fullName>
    <label>Bonus Assigned Date</label>
    <type>Date</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Member_Bonus__c/fields/Loyalty_Program_Setup_Rule__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Program_Setup_Rule__c</fullName>
    <label>Loyalty Program Setup Rule</label>
    <referenceTo>Loyalty_Program_Setup_Rules__c</referenceTo>
    <relationshipLabel>Loyalty Member Bonuses</relationshipLabel>
    <relationshipName>Loyalty_Member_Bonuses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Member_Bonus__c/fields/Loyalty_Value__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Value__c</fullName>
    <label>Loyalty Value</label>
    <referenceTo>Loyalty_Value__c</referenceTo>
    <relationshipLabel>Loyalty Member Bonuses</relationshipLabel>
    <relationshipName>Loyalty_Member_Bonuses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

LoyaltyApp/force-app/main/default/objects/Loyalty_Value__c/Loyalty_Value__c.object-meta.xml
<CustomObject>
    <label>Loyalty Value</label>
    <nameField>
        <label>Loyalty Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LoyaltyApp/force-app/main/default/classes/Loyalty_Util_MemberBonusDml.cls
/*
   @Author: João Almeida
   @CreatedDate: 30/09/2020
   @Description: Contains the CRUD methods for Loyalty_Member_Bonus__c SObject
 */
public with sharing class Loyalty_Util_MemberBonusDml extends Loyalty_Util_GenericDML {
    public class LoyaltyMemberBonusDmlException extends Exception {}

    public Loyalty_Util_MemberBonusDml() {
		super('Loyalty_Member_Bonus__c');
    }

    /*
        @Description: gets loyalty member bonus record by account and bonus rule
        @param1: account id
        @param2: bonus rule id
        @Return: the member bonus records
    */
    public List<Loyalty_Member_Bonus__c> getLoyaltyMemberBonusByAccountAndBonusRule(Id accountId, Id bonusRuleId) {
      List<Loyalty_Member_Bonus__c> memberBonuses = null;
        try {
            List<String> selectableFields = new List<String>{'Id','Account__c', 'Bonus_Assigned_Date__c', 'Loyalty_Program_Setup_Rule__c', 'Loyalty_Value__c'};
            List<String> orderBy = new List<String>{'Bonus_Assigned_Date__c'};
            List<String> whereClauses = new List<String>{'Account__c=\'' + accountId +'\'','and Loyalty_Program_Setup_Rule__c=\'' + bonusRuleId + '\''};
            memberBonuses = (Loyalty_Member_Bonus__c[])this.selectRecords(0, 0, null, null, selectableFields,whereClauses, orderBy, null, false, false);
        }
        catch (Exception ex) {
            throw ex;
        }

        return memberBonuses;
    }
}